name: add-to-project-gdev.yaml

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/${{ env.SENZING_GITHUB_ACCOUNT_NAME }}/projects/${{ env.SENZING_PROJECT_GDEV }}
          github-token: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}
